// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ToolsGenTable is the golang structure of table tools_gen_table for DAO operations like Where/Data.
type ToolsGenTable struct {
	g.Meta         `orm:"table:tools_gen_table, do:true"`
	TableId        interface{} // 编号
	TableName      interface{} // 表名称
	TableComment   interface{} // 表描述
	TplCategory    interface{} // 使用的模板（crud单表操作 tree树表操作）
	ObjectName     interface{} // 数据对象名称
	ApiFile        interface{} // api文件夹
	ControllerFile interface{} // controller文件夹
	ServerFile     interface{} // server文件夹
	FunctionName   interface{} // 生成功能描述
	FunctionAuthor interface{} // 生成功能作者
	Options        interface{} // 其它生成选项
	Remark         interface{} // 备注
	CreatedAt      *gtime.Time // 创建时间
	UpdatedAt      *gtime.Time // 更新时间
	DeletedAt      *gtime.Time // 删除时间
}
