// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysJobLog is the golang structure for table sys_job_log.
type SysJobLog struct {
	JobLogId      int64       `json:"jobLogId"      ` // 任务日志ID
	JobName       string      `json:"jobName"       ` // 任务名称
	JobGroup      string      `json:"jobGroup"      ` // 任务组名
	InvokeTarget  string      `json:"invokeTarget"  ` // 调用目标字符串
	JobParams     string      `json:"jobParams"     ` // 参数
	JobMessage    string      `json:"jobMessage"    ` // 日志信息
	Status        int         `json:"status"        ` // 执行状态（0正常 1失败）
	ExceptionInfo string      `json:"exceptionInfo" ` // 异常信息
	CreateTime    *gtime.Time `json:"createTime"    ` // 创建时间
}
