// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ToolsGenTable is the golang structure for table tools_gen_table.
type ToolsGenTable struct {
	TableId        int64       `json:"tableId"        ` // 编号
	TableName      string      `json:"tableName"      ` // 表名称
	TableComment   string      `json:"tableComment"   ` // 表描述
	TplCategory    string      `json:"tplCategory"    ` // 使用的模板（crud单表操作 tree树表操作）
	ObjectName     string      `json:"objectName"     ` // 数据对象名称
	ApiFile        string      `json:"apiFile"        ` // api文件夹
	ControllerFile string      `json:"controllerFile" ` // controller文件夹
	ServerFile     string      `json:"serverFile"     ` // server文件夹
	FunctionName   string      `json:"functionName"   ` // 生成功能描述
	FunctionAuthor string      `json:"functionAuthor" ` // 生成功能作者
	Options        string      `json:"options"        ` // 其它生成选项
	Remark         string      `json:"remark"         ` // 备注
	CreatedAt      *gtime.Time `json:"createdAt"      ` // 创建时间
	UpdatedAt      *gtime.Time `json:"updatedAt"      ` // 更新时间
	DeletedAt      *gtime.Time `json:"deletedAt"      ` // 删除时间
}
