// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ToolsGenTableColumn is the golang structure for table tools_gen_table_column.
type ToolsGenTableColumn struct {
	ColumnId         int64  `json:"columnId"         ` // 编号
	TableId          int64  `json:"tableId"          ` // 归属表编号
	ColumnName       string `json:"columnName"       ` // 列名称
	ColumnComment    string `json:"columnComment"    ` // 列描述
	ColumnType       string `json:"columnType"       ` // 列类型
	GoType           string `json:"goType"           ` // Go类型
	GoField          string `json:"goField"          ` // Go字段名
	HtmlField        string `json:"htmlField"        ` // html字段名
	IsPk             string `json:"isPk"             ` // 是否主键（1是）
	IsIncrement      string `json:"isIncrement"      ` // 是否自增（1是）
	IsRequired       string `json:"isRequired"       ` // 是否必填（1是）
	IsInsert         string `json:"isInsert"         ` // 是否为插入字段（1是）
	IsEdit           string `json:"isEdit"           ` // 是否编辑字段（1是）
	IsList           string `json:"isList"           ` // 是否列表字段（1是）
	IsQuery          string `json:"isQuery"          ` // 是否查询字段（1是）
	QueryType        string `json:"queryType"        ` // 查询方式（等于、不等于、大于、小于、范围）
	HtmlType         string `json:"htmlType"         ` // 显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）
	DictType         string `json:"dictType"         ` // 字典类型
	Sort             int    `json:"sort"             ` // 排序
	LinkTableName    string `json:"linkTableName"    ` // 关联表名
	LinkTableClass   string `json:"linkTableClass"   ` // 关联表类名
	LinkTablePackage string `json:"linkTablePackage" ` // 关联表包名
	LinkLabelId      string `json:"linkLabelId"      ` // 关联表键名
	LinkLabelName    string `json:"linkLabelName"    ` // 关联表字段值
}
